"""
Realistic mock tender data for DEMO_MODE.
Used when TINYFISH_API_KEY is not yet configured.
"""

from datetime import datetime, timedelta

_today = datetime.utcnow()

def _deadline(days: int) -> str:
    return (_today + timedelta(days=days)).strftime("%Y-%m-%d")


MOCK_TENDERS = [
    # ── GeM Portal ──────────────────────────────────────────────
    {
        "id": "mock-gem-001",
        "portal": "gem",
        "title": "Supply of HP Laptop Computers (Core i7, 16GB RAM) for Ministry of Finance",
        "reference_number": "GEM/2026/B/4521987",
        "department": "Ministry of Finance, Dept. of Economic Affairs",
        "value": 28500000,
        "deadline": _deadline(2),
        "location": "New Delhi",
        "description": "Supply and installation of 150 units HP EliteBook 840 laptops with Windows 11 Pro for department use. Delivery within 30 days of order.",
        "source_url": "https://gem.gov.in",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-gem-002",
        "portal": "gem",
        "title": "Annual Maintenance Contract for Network Infrastructure — CBDT",
        "reference_number": "GEM/2026/S/3817623",
        "department": "Central Board of Direct Taxes (CBDT)",
        "value": 12300000,
        "deadline": _deadline(8),
        "location": "Pan India",
        "description": "Comprehensive AMC for routers, switches, and firewalls deployed across CBDT offices in 28 states. Includes 24x7 NOC support.",
        "source_url": "https://gem.gov.in",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-gem-003",
        "portal": "gem",
        "title": "Procurement of Cloud Storage Services (AWS/Azure) — UIDAI",
        "reference_number": "GEM/2026/S/3901245",
        "department": "Unique Identification Authority of India (UIDAI)",
        "value": 856000000,
        "deadline": _deadline(21),
        "location": "New Delhi",
        "description": "Multi-year contract for scalable cloud storage and compute services for Aadhaar data processing infrastructure. Minimum 100TB storage.",
        "source_url": "https://gem.gov.in",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-gem-004",
        "portal": "gem",
        "title": "IT Security Audit and Penetration Testing Services — RBI",
        "reference_number": "GEM/2026/S/4102378",
        "department": "Reserve Bank of India",
        "value": 4750000,
        "deadline": _deadline(15),
        "location": "Mumbai",
        "description": "Comprehensive security audit including penetration testing, vulnerability assessment, and compliance checking for RBI's core banking systems.",
        "source_url": "https://gem.gov.in",
        "is_saved": True,
        "is_read": True,
    },

    # ── CPPP ────────────────────────────────────────────────────
    {
        "id": "mock-cppp-001",
        "portal": "cppp",
        "title": "Construction of Data Centre Building — NIC Phase III",
        "reference_number": "NIC/DC/2026/003",
        "department": "National Informatics Centre (NIC)",
        "value": 1250000000,
        "deadline": _deadline(35),
        "location": "Pune, Maharashtra",
        "description": "Design, supply, and construction of a Tier-3 certified data centre with 5MW IT load capacity. Includes civil, electrical, and HVAC work.",
        "source_url": "https://eprocure.gov.in/cppp",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-cppp-002",
        "portal": "cppp",
        "title": "Digital Literacy Mission — Tablets for Rural Schools (UP)",
        "reference_number": "MoE/DL/2026/TAB/0041",
        "department": "Ministry of Education",
        "value": 342000000,
        "deadline": _deadline(1),
        "location": "Uttar Pradesh",
        "description": "Supply of 50,000 tablets with preloaded educational content for government schools in rural Uttar Pradesh under PM e-VIDYA scheme.",
        "source_url": "https://eprocure.gov.in/cppp",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-cppp-003",
        "portal": "cppp",
        "title": "ERP Implementation for Integrated Financial Management System",
        "reference_number": "CGA/ERP/2026/007",
        "department": "Controller General of Accounts, Ministry of Finance",
        "value": 785000000,
        "deadline": _deadline(42),
        "location": "New Delhi",
        "description": "Implementation of SAP-based IFMS across 45 central government ministries with integration to PFMS and treasury systems.",
        "source_url": "https://eprocure.gov.in/cppp",
        "is_saved": False,
        "is_read": False,
    },

    # ── Defence Tenders ─────────────────────────────────────────
    {
        "id": "mock-mod-001",
        "portal": "mod",
        "title": "Supply of Encrypted Communication Radios — Indian Army Signal Corps",
        "reference_number": "MOD/ARMY/SIG/2026/018",
        "department": "Ministry of Defence — Army Signal Corps",
        "value": 2340000000,
        "deadline": _deadline(60),
        "location": "Delhi Cantonment",
        "description": "Procurement of 2,000 units tactical encrypted VHF/UHF radio sets with AES-256 encryption for field deployment. Indigenous content minimum 50%.",
        "source_url": "https://mod.gov.in/tenders",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-mod-002",
        "portal": "mod",
        "title": "IT Infrastructure Modernization — Defence Accounts Department",
        "reference_number": "MOD/DAD/IT/2026/004",
        "department": "Defence Accounts Department (DAD)",
        "value": 156000000,
        "deadline": _deadline(5),
        "location": "Pune",
        "description": "Replacement of end-of-life servers, storage, and networking equipment for DAD offices across India. Includes 3-year support contract.",
        "source_url": "https://mod.gov.in/tenders",
        "is_saved": False,
        "is_read": False,
    },

    # ── IREPS / Railways ────────────────────────────────────────
    {
        "id": "mock-ireps-001",
        "portal": "ireps",
        "title": "Supply of Railway Station WiFi Equipment — 500 Stations",
        "reference_number": "IR/CRIS/WIFI/2026/022",
        "department": "Centre for Railway Information Systems (CRIS)",
        "value": 890000000,
        "deadline": _deadline(28),
        "location": "Pan India",
        "description": "Supply and installation of WiFi access points, controllers, and backhaul equipment for 500 non-A1/A category railway stations under RailWire expansion.",
        "source_url": "https://www.ireps.gov.in",
        "is_saved": False,
        "is_read": False,
    },
    {
        "id": "mock-ireps-002",
        "portal": "ireps",
        "title": "Passenger Reservation System (PRS) Maintenance Contract",
        "reference_number": "IR/CRIS/PRS/2026/005",
        "department": "CRIS / Indian Railways",
        "value": 234000000,
        "deadline": _deadline(9),
        "location": "New Delhi",
        "description": "Annual maintenance, enhancement, and 24x7 operations support for the PRS serving 14 million passengers daily. Includes helpdesk and onsite support.",
        "source_url": "https://www.ireps.gov.in",
        "is_saved": False,
        "is_read": False,
    },

    # ── NHAI ────────────────────────────────────────────────────
    {
        "id": "mock-nhai-001",
        "portal": "nhai",
        "title": "FASTag Infrastructure Upgrade — Toll Plaza ANPR Cameras",
        "reference_number": "NHAI/FT/ANPR/2026/031",
        "department": "National Highways Authority of India",
        "value": 445000000,
        "deadline": _deadline(18),
        "location": "Gujarat, Rajasthan",
        "description": "Supply and installation of Automatic Number Plate Recognition (ANPR) cameras at 320 toll plazas across NH-48 and NH-27. Includes integration with FASTag backend.",
        "source_url": "https://nhai.gov.in/tenders",
        "is_saved": False,
        "is_read": False,
    },
]
